FROM mysql:8.0

#RUN mkdir -p /etc/mysql/data \
#  && chown -R app:app /etc/mysql/data \

#COPY ./docker/images/mysql/db/magento.sql.gz /etc/mysql/data
#COPY ./docker/images/mysql/db/magento.sql.gz /docker-entrypoint-initdb.d
#COPY ./docker/images/mysql/conf/my.cnf /etc/mysql/conf.d/

#COPY ./docker/images/mysql/settings/init_data.sh .
#RUN ["sh", "./init_data.sh"]
