alias mage='XDEBUG_MODE=off bin/magento'
alias deploy='rm -rf var/view_preprocessed/ var/cache/ var/page_cache/ generated/ pub/static/adminhtml/ && XDEBUG_MODE=off composer require mageplaza/module-smtp && XDEBUG_MODE=off composer install && mage module:disable Magento_TwoFactorAuth && mage set:up && mage set:di:com && mage setup:static-content:deploy -f en_US -a adminhtml && mage c:c'
alias sog='XDEBUG_MODE=off ./n98-magerun2.phar sys:cron:run sales_grid_order_async_insert'
alias gt='echo "glpat-1ssDHNYnaxzmw837SxJY" && git fetch --prune && git config credential.helper "cache --timeout=3600000"'
alias ap='php -n -d memory_limit=-1 ./vendor/bin/ece-patches apply'
alias dpf='rm -rf var/view_preprocessed/ var/cache/ var/page_cache/ generated/ pub/static/adminhtml/ && mage module:disable Magento_TwoFactorAuth && mage set:up && mage set:di:com && mage setup:static-content:deploy -f en_US -a adminhtml && mage c:c'
